### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by TorinTurner** [druv5319/Sneaks-API#18]
Nothing is working getting a 403. Your site isn’t working either.

**Comment by TorinTurner** [comment]
May be an issue with scrapers. Am unsure.

**Comment by RamsesRomeroJr** [comment]
I noticed too... From what I saw the error began in scrapers/stockx-scraper.js 
the page it's trying to hit returns ``` {
message: "Invalid Application-ID or API key",
status: 403
} ```

which then breaks on line 62 as well saying shoe is undefined
my guess is his algolia API Key is no longer active 

but everything i've tried to fix just breaks ;( hopfully it gets fixed before next thursday I gotta present this project I created based around the scrapers

**Comment by TorinTurner** [comment]
Assumed had to be with StockX haha. I will take a second look at it tomorrow and have a go at it.

**Comment by RamsesRomeroJr** [comment]
If you figure something out please let me know!!! I was bumping my head all day with it haha

**Comment by jakelax-ctrl** [comment]
Having the same problem. Also, when I'm running on the command line, it has been saying that are two vulnerabilities and when I audit it, it states that the version of axios is vulnerable and that there's a server side request forgery. I'm assuming that that's an api issue right, not anything that I can update to fix?

**Comment by FrancescoMontanaro** [comment]
I found out that the problem is related to the StockX scraper and in particular about the API key of the Angolia API.
In other words, It seems that StockX has changed its API key.
To fix the problem you have to change something in the stockx-scraper.js file, in the following way:

1) Navigate to the 'node-modules' folder in your PC. 
2) Navigate to the file sneaks-api --> scrapers --> stockx-scraper.js
3) open the stockx-scraper.js file with a code editor such as VSCode.
4) At line 9 you can find the following endoint: 'https://xw7sbct9v6-1.algolianet.com/1/indexes/products/query?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%203.32.1&x-algolia-application-id=XW7SBCT9V6&x-algolia-api-key=OLD_API_KEY'
5) Replace the OLD_API_KEY with the following key: 6b5e76b49705eb9f51a06d3c82f7acee (I've found it by inspecting the StockX XHR requests).
6) Save and launch again the API. Now it should work.

**Comment by RamsesRomeroJr** [comment]
wow thanks that seemed to fix it!! I spent all weekend creating a bunch of back up data but now I got the scrapers running again just gotta undo everything I had done lmao 

LIFE SAVOR @FrancescoMontanaro

**Comment by tylerwertman** [comment]
Any chance this is the issue again? 
Or did it break somewhere else. I went to change that key but it was already at that value
